### ISSUE TITLE
As someone who likes a smooth experience, I want to interact with the pages and features of the application so that those interactions to another page/feature have a visible transition

### ISSUE THREAD

**Issue by vwong175** [cse442-at-ub/project_s23-iweatherify#104]
**Acceptance Tests**

*Test 1*
1) Go to the deployed version of the repo: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/
2) Click on the menu icon and click on login
3) Sign in with the credentials of "sprint4" and "Sprint1234!"
4) Click on the menu icon
5) Verify that the menu transitions opening from the top to bottom
6) Click on the next tab underneath this current tab
7) Verify that you are navigated to another page where the page fades in
8) Repeat steps 5 - 7 until you visited each tab in the menu

**Comment by junqiwu02** [comment]
"iWeatherify participant" is a bit too general of a description, "someone who likes a smooth experience" is more appropriate
