### ISSUE TITLE
Add transitions to each visited page and slide in to menu

### ISSUE THREAD

**Issue by vwong175** [cse442-at-ub/project_s23-iweatherify#105]
**Task Tests**

*Test 1*
1) Go to the repo
2) Git clone the repo and cd into the root of the project
3) Run npm install and npm run start
4) Go to the page where the app is running and click on the hamburger menu to login with the credentials of "sprint4" and "Sprint1234!"
5) Click on the menu icon
6) Verify that the menu transitions opening up from the top to bottom
7) reclick on the menu icon and verify it closes from bottom to top.
8) Reopen the menu bar and click on the next tab underneath this current tab
9) Verify that you are navigated to another page where the page fades in
10) Repeat steps 5 - 9 until you visited each tab in the menu

*Test 2*
1) Follow steps 1 - 5 from test 1
2) Click on the settings tab
3) Click on "Location Settings" and verify that there is a fade in transition
4) Click on "Temperature Settings" and verify that there is a fade in transition
5) Click on "Account Settings" and verify that there is a fade in transition

*Test 3*
1) Follow steps 1 - 3 from test 1
2) Click on the hamburger menu and if there is an option to log out, click on that. Otherwise, click on the log in tab
3) Verify that the log in page loaded with a fade in transition
4) Click on the hamburger menu again and click on register. Verify that the register page loaded with a fade in transition

**Comment by junqiwu02** [comment]
add a test for the settings page transitions
