### ISSUE TITLE
As a person without any saved outfits, I want to navigate to the Saved Outfits page so that I can see a suggestion to save an outfit from the homepage

### ISSUE THREAD

**Issue by vwong175** [cse442-at-ub/project_s23-iweatherify#106]
**Acceptance Tests**

*Test 1*
1) Go to the deployed version of the app at: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/
2) Click on the hamburger menu and click on login
3) Login with the credentials "demo123" and "Demo123456!"
4) Click on the hamburger menu again and click on "saved outfits"
5) Verify that there are no saved outfits and that there is an icon with some text suggesting to save an outfit from the homepage

**Comment by junqiwu02** [comment]
add the link to the page
