### ISSUE TITLE
Design for Empty State of Saved Outfits page

### ISSUE THREAD

**Issue by vwong175** [cse442-at-ub/project_s23-iweatherify#107]
**Task Tests**

*Test 1*
1) Go to the repo at: https://github.com/cse442-at-ub/project_s23-iweatherify/tree/dev
2) Clone the repo and cd into the root of the project. Run npm install and npm run start. Then navigate to the page in a browser where the app is running.
3) Click on the hamburger menu and click on login
4) Login with the credentials "demo123" and "Demo123456!"
5) Click on the hamburger menu again and click on "saved outfits"
6) Verify that there are no saved outfits and that there is an icon with some text suggesting to save an outfit from the homepage

**Comment by junqiwu02** [comment]
add the link
