### ISSUE TITLE
Make design and add prototyping interactivity for the forgot password frame 

### ISSUE THREAD

**Issue by vwong175** [cse442-at-ub/project_s23-iweatherify#11]
**Task Test**

*Test 1*
1) Head into figma design (https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=0bYV0rMFBe8FbA2l-1)
2) Observe that the frame titled "Website - Forgot password" design has an input box element, a button to reset password, and text to go back to the login page
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/73c5d62d-c029-4c73-8732-8c5b9713c85e)
3) Observe that the frame titled "Mobile - Forgot password" design has an input box element, a button to reset password, and text to go back to the login page
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/3af64e67-4db8-4ea6-8721-eadeb1d44de1)

*Test 2*
1) Head into figma design (https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=0bYV0rMFBe8FbA2l-1)
2) Click on the triangle button on the top right hand corner
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/6d0d6067-2743-44d5-8f70-506eba642ead)
3) On the left hand panel, click "Desktop flow - not logged in" and ensure there is a checkmark to the left of the text
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/ed7e58d6-32ca-4e3a-b6db-59414f4ec7de)
4) On the upper right hand corner, click on the circle with an empty profile picture
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/508b2551-7504-4353-9860-fba1bb2ded0a)
5) Ensure you are now located to the login page. Click on "Forgot password" located under the password input element
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/e81a13df-7f58-42ef-a720-89adb2541c60)
6) Verify that you have navigated to the "forgot password" frame with an input element box, a button to reset your password, and text to go back to the login page.
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/2cd33a6f-6c23-48d0-85f1-163829e46af9)
7) Click on "Reset password" button
8) Ensure that you see a modal appear stating that a reset email was sent out
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/9539ccc6-3c7e-410f-b61d-25c8a162a352)

**Comment by junqiwu02** [comment]
Make sure this is a dependency of a story! #9 makes sense
