### ISSUE TITLE
Create and add prototyping interactivity for the Menu Bar frame

### ISSUE THREAD

**Issue by JayXPan** [cse442-at-ub/project_s23-iweatherify#12]
**Task tests**

*Test 1*
1) Open the Figma file for iWeatherify using this link: https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=0bYV0rMFBe8FbA2l-1
2) Click on the "Play" button, top right of the page, to start the interactive demo, and select "Desktop - logged in" to begin the flow
![Play Button](https://user-images.githubusercontent.com/112517521/219908195-3048cb15-ff44-4e60-9875-9c86cdd8ad07.png)
![Desktop flow - logged in](https://user-images.githubusercontent.com/112517521/219908246-b6684815-b990-462d-b6cc-2c5b8cdb8cc5.png)
3) Locate the menu bar (4 horizontal lines on the top right of the web page) on the top right of the web pages: Home Page, Profile Page, Temperature Setting Page, Help Page, My Items Page, Units Page, General Setting Page, and others
![Menu Bar](https://user-images.githubusercontent.com/112517521/219908327-1ca006f9-f114-4727-99f0-a5363b7f5ce3.png)
4) Click on the menu bar to reveal the menu options
5) You should see the following options: Home, Profile, Units, My Items, Temperature, and Help

*Test 2*
1) Repeat the same step 1 from "Test 1"
2) Click on the "Play" button, top right of the page, to start the interactive demo, and select "Desktop - not logged in" to begin the flow
![Play Button](https://user-images.githubusercontent.com/112517521/219908195-3048cb15-ff44-4e60-9875-9c86cdd8ad07.png)
![Desktop flow - not logged in](https://user-images.githubusercontent.com/112517521/219908847-9383bea7-253c-4954-b0f0-316a6e6ec4b7.png)
3) Locate the menu bar (4 horizontal lines on the top right of the web page) on the top right of the web page
![Menu Bar (1).png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/f534bb54-d386-4ea6-a0cf-dd816d97b5e3)
4) Verify that the menu bar is unresponsive and cannot be clicked

**Comment by junqiwu02** [comment]
This should be a _blocking_ dependency for #9 instead of being _blocked_ by it.
