### ISSUE TITLE
Design and add prototyping interactivity into "My Items" frame

### ISSUE THREAD

**Issue by vwong175** [cse442-at-ub/project_s23-iweatherify#13]
**Task Tests**

*Test 1*
1) Go to figma file (https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=0bYV0rMFBe8FbA2l-1)
2) Click on the "Play" button, top right of the page, to start the interactive demo, and select "Desktop - logged in" to begin the flow
![Play Button](https://user-images.githubusercontent.com/112517521/219908195-3048cb15-ff44-4e60-9875-9c86cdd8ad07.png)
![Desktop flow - logged in](https://user-images.githubusercontent.com/112517521/219908246-b6684815-b990-462d-b6cc-2c5b8cdb8cc5.png)
3) Click on the hamburger more menu located on the top right hand corner
![Menu Bar](https://user-images.githubusercontent.com/112517521/219908327-1ca006f9-f114-4727-99f0-a5363b7f5ce3.png)
4) Click on "My Items"
5) Verify that you are brought to a new page titled "My Items" with six categories of options: "Hot", "Warm", "Just right", "Chilly", "Cold", "Freezing"

*Test 2*
1) Go to figma file (https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=0bYV0rMFBe8FbA2l-1)
2) Click on the "Play" button, top right of the page, to start the interactive demo, and select "Mobile flow"
![Play Button](https://user-images.githubusercontent.com/112517521/219908195-3048cb15-ff44-4e60-9875-9c86cdd8ad07.png)
3) Click on the hamburger menu located on the top left hand corner
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/534e5c49-008d-4674-8454-463ae8dc4af0)
4) Click on "My Items"
5) Verify that you are brought to a new page titled "My Items" with six categories of options: "Hot", "Warm", "Just right", "Chilly", "Cold", "Freezing"

**Comment by junqiwu02** [comment]
![image](https://user-images.githubusercontent.com/22561215/219808329-a55c928c-c409-452f-a12f-9eeb2d0fc647.png)
This is a example screenshot
