### ISSUE TITLE
Creating PHP Documentation

### ISSUE THREAD

**Issue by shlc001** [cse442-at-ub/project_s23-iweatherify#14]
**Task Tests**

*Test 1*
1) Open the Google Document called “PHP Documentation”
https://docs.google.com/document/d/1f2W6JGzp1QbLZvDrYjKrBlevV2UbyYYYefAmMZBztbA/edit
2) Read the “Getting Started with PHP” section
3) Read the “Recommended PHP Resources” section
4) Read the “Connecting to UB Servers” section
5) Complete the tutorial

**Comment by junqiwu02** [comment]
Add a link to the doc in the test! Also "achieve basic mastery" is not a very measurable/observable outcome. If the tutorial includes a demo app, assert that that works instead.
