### ISSUE TITLE
Creating documentation for potential frontend frameworks with pros and cons of each framework 

### ISSUE THREAD

**Issue by ccherian007** [cse442-at-ub/project_s23-iweatherify#16]
Task Tests 

1. **https://docs.google.com/document/d/1VPASw7b6GKhC09t9R5XjnwVZZTecglqjZ93R-RkcHf8/edit** refer to this

**Comment by junqiwu02** [comment]
Every task needs task test(s)! Since research tasks might not have an observable outcome, you just put the link and say "refer to this".
