### ISSUE TITLE
Make design for "Home page logged in" frame

### ISSUE THREAD

**Issue by jhe48** [cse442-at-ub/project_s23-iweatherify#18]
**Task Test**

_Test 1_

1. Open the Figma file for iWeatherfy using this link: https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=hBE4ejilNA7ee649-0

2. Observe that the frame titled "Home page not logged in" design has text "Login to view a personalized outfit of the day!"
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/bcd9a5ac-957e-4311-a6ac-676cb20a883d)
3. Observe that the frame titled "Home page logged in" design has an image and does not have text "Login to view a personalized outfit of the day!"
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/7fdde57d-a5fc-45f6-ba94-0f97e3d9aabc)

_Test 2_

1. Open the Figma file for iWeatherfy using this link: https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=hBE4ejilNA7ee649-0

2. Click on the triangle button in the top right hand corner.
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/b8ed9e26-2db9-4bec-99e8-1e8b0001d952)
3. On the left hand panel, click "Desktop flow - not logged in".
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/d78e8e6e-ec69-41e2-bf62-41b623d42207)
4. Ensure there is the text "Login to view a personalized outfit of the day!"
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/ba7d7e55-4e7d-4cd0-8549-0531a736a479)

_Test 3_

1. Open the Figma file for iWeatherfy using this link: https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=hBE4ejilNA7ee649-0

2. Click on the triangle button in the top right hand corner.
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/b8ed9e26-2db9-4bec-99e8-1e8b0001d952)
3. On the left hand panel, click "Desktop flow - logged in".
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/0ef02851-2f30-4d24-821c-8898742d1235)
4. Ensure there is this image instead of the text "Login to view a personalized outfit of the day!"
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/46601044-c89e-46ce-a4c7-ab7275aff29d)

**Comment by junqiwu02** [comment]
Make this a dependency of a user story! #9 Most likely makes sense. Also add an assignee
