### ISSUE TITLE
Make design for "Profile" frame

### ISSUE THREAD

**Issue by jhe48** [cse442-at-ub/project_s23-iweatherify#19]
**Task Test**

_Test 1_

1. Open the Figma file for iWeatherfy using this link: https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=hBE4ejilNA7ee649-0

2. Observe that the frame titled "Profile" design has an image.
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/8aa2208c-f795-4ff2-a591-949250fc5bd3)

_Test 2_

1. Open the Figma file for iWeatherfy using this link: https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=hBE4ejilNA7ee649-0

2. Click on the triangle button in the top right hand corner.
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/b8ed9e26-2db9-4bec-99e8-1e8b0001d952)
3. On the left hand panel, click "Desktop flow - logged in".
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/0ef02851-2f30-4d24-821c-8898742d1235)
4. On the right hand side of the page, locate and click the profile icon. 
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/7de4ba4d-961a-47fc-b5bc-6c767ef2e020)
5. Ensure there is this image on the page. 
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/8aefeef1-61dd-4501-8dff-8cfb53c6ea75)

_Test 3_

1. Open the Figma file for iWeatherfy using this link: https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=hBE4ejilNA7ee649-0

2. Click on the triangle button in the top right hand corner.
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/b8ed9e26-2db9-4bec-99e8-1e8b0001d952)
3. On the left hand panel, click "Desktop flow - logged in".
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/0ef02851-2f30-4d24-821c-8898742d1235)
4. On the right hand side of the page, locate and click the menu icon. 
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/3a559057-1cb6-47b0-a0ed-eff3242187e2)
5. From the menu options, click "Profile".
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/416d5bcd-f6db-42bd-a2c1-aeff1b78d46c)
6. Ensure there is this image on the page. 
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/8aefeef1-61dd-4501-8dff-8cfb53c6ea75)

**Comment by junqiwu02** [comment]
Make this a dependency of a user story! #9 Most likely makes sense. Also add an assignee
