### ISSUE TITLE
Design and implement interactivity that allows users to enable/disable their current location

### ISSUE THREAD

**Issue by ccherian007** [cse442-at-ub/project_s23-iweatherify#31]
Task Tests

Test 1

1. Go to Figma file: https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=UPpVMyqPlJZUSvbg-0

2. Click on the "Play" icon, located on the top right of the page, to start the interactive demo, and select "Desktop-logged in" to begin the flow 
 ![Screenshot 2023-02-25 at 1.10.35 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/50689dcf-7778-4b05-ba4a-30ca5931504a)
![Screenshot 2023-02-25 at 1.11.05 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/e4d181f7-5281-4362-a160-5ddde577d028)
3. Make sure your on the homepage 
![Screenshot 2023-02-25 at 1.11.57 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/bb73ae00-a0c3-4067-9837-f7ed701b8d2c)5. Click toggle button to enable current location 
4. Click on the menu bar (Four horizontal lines at the top right corner of the page) and  then click on "Location" 
![Screenshot 2023-02-25 at 1.12.18 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/071093f9-3577-4672-8ed9-ef7e21b74e10)
![Screenshot 2023-02-25 at 1.12.54 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/e2e046f3-5b1b-458a-9dfd-49ece496667d)

5. Click toggle button to enable current location 
![Screenshot 2023-02-25 at 1.13.12 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/ffd77d02-3e60-44f5-ac27-0a732c933a11)
6. Click toggle button again to disable current location
![Screenshot 2023-02-25 at 1.13.38 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/337778a0-9c1d-4f5f-8a02-145c4568312e)
7. Click save button to save changes 
![Screenshot 2023-02-25 at 1.13.59 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/a1756cb4-0689-4b4b-a8a8-1f4c03faebeb)

**Comment by junqiwu02** [comment]
Add an assignee
