### ISSUE TITLE
Design and implement interactivity that allows users to enter a location of their choice

### ISSUE THREAD

**Issue by ccherian007** [cse442-at-ub/project_s23-iweatherify#32]
Task Tests

Test 1

1. Go to Figma file: https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=UPpVMyqPlJZUSvbg-0

2. Click on the "Play" icon, located on the top right of the page, to start the interactive demo, and select "Desktop-logged in" to begin the flow 
 ![Screenshot 2023-02-25 at 1.10.35 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/50689dcf-7778-4b05-ba4a-30ca5931504a)
![Screenshot 2023-02-25 at 1.11.05 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/e4d181f7-5281-4362-a160-5ddde577d028)

3. Make sure your on the homepage 
![Screenshot 2023-02-25 at 1.11.57 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/bb73ae00-a0c3-4067-9837-f7ed701b8d2c)

4. Click on the menu bar (Four horizontal lines at the top right corner of the page) and  then click on "Location" 
![Screenshot 2023-02-25 at 1.12.18 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/071093f9-3577-4672-8ed9-ef7e21b74e10)
![Screenshot 2023-02-25 at 1.12.54 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/e2e046f3-5b1b-458a-9dfd-49ece496667d)

5. Put in any city name or zip code 
Note: Figma doesn't save user input so input cannot be saved and displayed but it will be implemented in our code
![Screenshot 2023-02-25 at 1.48.59 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/b2da06be-be9f-4815-988d-f814cfbfd538)

**Comment by junqiwu02** [comment]
Add someone as an assignee!
