### ISSUE TITLE
Make Design for Logo

### ISSUE THREAD

**Issue by jhe48** [cse442-at-ub/project_s23-iweatherify#33]
**Task Test**

_Test 1_

1. Open the Figma file for iWeatherfy using this link: https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=hBE4ejilNA7ee649-0

2. Observe that the frame titled "Website - Home page logged in" design has the logo displayed in the top right corner of the frame: 
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/67ef30e3-e2a9-470d-b49c-3cad65b18539)

3. Observe that the frame titled "Website - Home page not logged in" design has the logo displayed in the top right corner of the frame: 
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/5502563a-8204-40f2-a26c-851c2e882910)

_Test 2_

1. Open the Figma file for iWeatherfy using this link: https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=hBE4ejilNA7ee649-0

2. Click on the triangle button in the top right hand corner.
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/b8ed9e26-2db9-4bec-99e8-1e8b0001d952)
3. On the left hand panel, click "Desktop flow - logged in".
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/0ef02851-2f30-4d24-821c-8898742d1235)
4. On the right hand side of the page, locate and click the menu icon. 
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/bc895c0d-c20e-4bc6-81ee-d390139ebb43)
5. Click on an option.
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/c0c3dc93-71b8-4bc7-aa15-6e66afae481c)
6. Ensure that the logo shown below is on the top corner of every webpage.
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/06867e7e-85f2-42f8-bd1a-de355d0c3ed8)
6. Repeat steps 4 and 5 until all options have been chosen at least once.

**Comment by junqiwu02** [comment]
Make this a dependency of a user story, #9 works

**Comment by junqiwu02** [comment]
Was the logo modified? If so, it should've gone into the In Progress pipeline first.

**Comment by junqiwu02** [comment]
Add sprint 2 label as well
