### ISSUE TITLE
Convert HTML/CSS Homepage into a Vue.js Homepage for Desktop and Mobile

### ISSUE THREAD

**Issue by shlc001** [cse442-at-ub/project_s23-iweatherify#36]
**Tests**

*Test 1*
1) Go to https://github.com/cse442-at-ub/project_s23-iweatherify/tree/Bugfix_Static_Homepage_To_Vue
2) Click on <> Code and download ZIP
3) Unzip the code
4) Enter the folder via terminal and run `npm install` (Or via IDE)
**Make sure you have npm installed or just run a localhost version on cheshire**
5) Run the command `npm start` (Or via IDE)
6) Open via localhost, which in my case it's (http://localhost:1234), but it should be provided by the output from `npm start`

*Test 2*
1) Do Test 1
2) Visit the path https://[local host here]/#/homepage-logged-in
3) Confirm that there's a logged-in version of the site!

*Test 3*
1) Do Test 1
2) Visit the homepage non-logged in version (https://[local host here]/#/)
3) Go to inspect elements
4) Click on Toggle Device Toolbar
5) Check Responsiveness on a variety of devices

*Test 4*
1) Do Test 1
2) Visit the path https://[local host here]/#/homepage-logged-in
3) Go to inspect elements
4) Click on Toggle Device Toolbar
5) Check Responsiveness on a variety of devices

**Comment by shlc001** [comment]
Appears to be in working order for localhost

**Comment by shlc001** [comment]
Discovered that the UB server is running node on v12.22.12, while I was running on the latest version. So, it wasn't working properly (Need to downgrade)

**Comment by junqiwu02** [comment]
I think this task would be more appropriate as dependency of a user story associated with the home page of the application.

**Comment by junqiwu02** [comment]
Add making mobile ver to title or as a separate task

**Comment by shlc001** [comment]
Discovered Responsiveness Issues on smaller devices (Small Typo Caused this)
