### ISSUE TITLE
As an international traveler with an account, I want to be able to update the different temperature units on the logged-in homepage, so that I can factor in my preferences

### ISSUE THREAD

**Issue by vwong175** [cse442-at-ub/project_s23-iweatherify#4]
**Acceptance Tests**

*Test 1*
1) Visit https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/register
2) Enter a valid email address, username, and password 
5) Click on register. You should get a popup telling you it is valid and remember to save the information you put in
6) Then go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/login
7) Put the valid information on the login page and press Login
8) Check to confirm your newly registered account has the defaults unit of Fahrenheit, mph for wind speed, and Hg for pressure 
![Screenshot 2023-04-07 at 4.40.14 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/bed30b69-b545-45b7-b12a-1b26c6a46b59)
9) As a logged-in user visit the Unit Settings page by clicking on Settings and then Clicking on Unit Settings
![Screenshot 2023-04-07 at 4.38.56 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/5facff28-6882-4643-907b-61941c97f580)
10) Change the default Temperature from °F to °C
11) Change The Wind option from mph to km/h
12) Change for Pressure Hg to mb
13) Click on Save 
![Screenshot 2023-04-07 at 4.42.50 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/6d8a451e-f567-47f3-b406-94b90d4ddad3)
14) Visit the logged-in homepage
https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/homepage
15) Confirm that the units have changed to C for temperature, km/h for Wind Speed and mb for Pressure
![Screenshot 2023-04-07 at 5.10.01 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/cfd21813-feaa-4df2-8a72-a4dc0aba5187)

*Test 2*
1) After completing test 1 go back to the unit settings page
https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/unitsSettings
2) Check that the Temperature has °C, Wind on km/h, and pressure on MB
![Screenshot 2023-04-07 at 5.07.25 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/5c362a17-d4a7-49b3-9e92-f658419b002d)
3) Change the default Temperature from °C to °F
4) Change The Wind option from km/h to mph
5) Change for Pressure mb to to Hg
6) Click on Save 
![Screenshot 2023-04-07 at 5.08.17 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/ea5565f9-3fed-4a9a-a242-0420b1b69d0a)
7) Visit the logged-in homepage
https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/homepage
8) Confirm that the units have changed to F for temperature, mph for Wind Speed and Hg for Pressure
![Screenshot 2023-04-07 at 5.09.12 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/00675b7f-4436-4ca1-9638-8001ebf8c8fa)

**Comment by junqiwu02** [comment]
add a test to verify changing back to the original units works
