### ISSUE TITLE
Create static Vue page for temperature control on desktop and mobile

### ISSUE THREAD

**Issue by JayXPan** [cse442-at-ub/project_s23-iweatherify#40]
**Task Tests**

*Test 1*
1) Navigate to https://github.com/cse442-at-ub/project_s23-iweatherify/tree/Temperature_Setting_Page
2) Click on the green "<> Code" button and download the ZIP file.
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/75c741f7-5ca3-4f64-879f-df960ad51a8b)
3) Unzip the downloaded file to a folder on your computer.
4) Open a terminal and navigate to the git repository folder using the `cd` command.
5) Run `npm install` in the terminal to install the necessary dependencies.
6) Run `npm start` in the terminal to start the application.
7) Check the output from npm start for the URL to access the application, which should be a localhost address (e.g., http://localhost:8080).
8) Open the application in a web browser using this URL: http://localhost:8080/#/website-temperature-settings-page
9) Verify you can see the temperature setting page
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/6a410dfd-bf18-4a23-a998-84b459ce1898)

*Test 2*
1. Repeat steps 1 through 8 from "Test 1"
2. Open the browser inspector tool and change the viewport to a mobile device
3. Check that you are able to view the temperature settings page on the mobile viewport. The page should resemble the picture shown below
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/8950f544-5bc8-4ba1-b069-0db028fd9bf3)

**Comment by junqiwu02** [comment]
Add a test to make sure the mobile view looks good as well
