### ISSUE TITLE
Create static Vue page for units on desktop and mobile

### ISSUE THREAD

**Issue by JayXPan** [cse442-at-ub/project_s23-iweatherify#41]
**Task Tests**

*Test 1*
1) Navigate to https://github.com/cse442-at-ub/project_s23-iweatherify/tree/Units_Page
2) Click on the green "<> Code" button and download the ZIP file.
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/75c741f7-5ca3-4f64-879f-df960ad51a8b)
3) Unzip the downloaded file to a folder on your computer.
4) Open a terminal and navigate to the git repository folder using the `cd` command.
5) Run `npm install` in the terminal to install the necessary dependencies.
6) Run `npm start` in the terminal to start the application.
7) Check the output from npm start for the URL to access the application, which should be a localhost address (e.g., http://localhost:8080).
8) Open the application in a web browser using this URL: http://localhost:8080/#/website-units-page
9) Verify you can see the units page
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/3972d5e6-33ad-404a-8dff-e038b2a70528)

*Test 2*
1. Repeat steps 1 through 8 from "Test 1"
2. Open the browser inspector tool and change the viewport to a mobile device
3. Check that you are able to view the unit settings page on the mobile viewport. The page should resemble the picture shown below
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/43def7ea-4ed3-4373-80c1-e5b847c2bdda)

**Comment by JayXPan** [comment]
The Units Table appears to display correctly on my desktop, but it looks strange on my laptop. I have tried adjusting some of the numbers and even commented out the table row flex container to see if it would help, but the changes are not being reflected for the 4 unit table rows.

**Comment by junqiwu02** [comment]
Add a test for mobile viewport
