### ISSUE TITLE
Create Static Vue Page for My Items for Desktop and Mobile 

### ISSUE THREAD

**Issue by ccherian007** [cse442-at-ub/project_s23-iweatherify#42]
**Task Tests**

*Test 1*

1. Navigate to page:  https://github.com/cse442-at-ub/project_s23-iweatherify/tree/dev

2. Click on the green "<> Code" button and select "Download Zip" to download zip file
![Screenshot 2023-03-06 at 9.16.43 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/bea9f8dd-e55e-4641-be4e-56adad99ed95)

3. Unzip the file to a folder on your computer

4. Open a terminal and locate the git repository folder using **cd** command

5. Run **npm install** to install necessary dependencies 

6. Run **npm start** to start the application

7. Open the application in a web browser using this URL: http://localhost:8080/#/website-my-items

8. Verify you can see the My Items Page:
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/b3720c16-f0a9-46a9-945b-537371d957ef)

*Test 2*
1. Repeat steps 1-7 from Test 1

2. Click this icon to open the application in mobile view
![Screenshot 2023-03-12 at 10.31.49 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/e4fbf842-9573-4a01-8804-9527f693137e)

3. On the left side of the window, near the top it should say "Dimensions:" and an option. Click on IphoneSE and verify that you are still able to see the contents of My Items Page.
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/2db5624a-63ed-48fc-9f55-f95acfe4f0b2)
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/5b041fb5-3f98-44f2-89b9-3a481873ffbd)

4. Repeat step 3 but go through each of the mobile options from the dropdown list

**Comment by junqiwu02** [comment]
Add as dependency of user story

**Comment by junqiwu02** [comment]
This should be a blocking dependency not a blocked by

**Comment by junqiwu02** [comment]
Add a test to assert at it looks good from mobile
