### ISSUE TITLE
Create Static Vue Page for Locations on Desktop and Mobile

### ISSUE THREAD

**Issue by ccherian007** [cse442-at-ub/project_s23-iweatherify#43]
Task Tests

**Test 1**

1. Navigate to page:  https://github.com/cse442-at-ub/project_s23-iweatherify/tree/dev

2. Click on the green "<> Code" button and select "Download Zip" to download zip file
![Screenshot 2023-03-06 at 9.16.43 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/bea9f8dd-e55e-4641-be4e-56adad99ed95)

3. Unzip the file to a folder on your computer

4. Open a terminal and locate the git repository folder using **cd** command

5. Run **npm install** to install necessary dependencies 

6. Run **npm start** to start the application

7. Open application in a web browser using this URL: http://localhost:8080/#/locationSettings

8. Verify you can see the Location Settings Page:
![Screenshot 2023-03-18 at 2.28.55 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/80a66c98-10e0-4925-b6fc-b1ee97672c90)

**Test 2**
1. Repeat steps 1-7

2. Right click on webpage and select Inspect. And click on this icon to open application in mobile view 
![Screenshot 2023-03-12 at 10.31.49 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/95751a6d-5853-4e9b-9687-e88ffcaf33b9)

3. Set dimensions to iPhone12 Pro and verify you can see the mobile view of the Location Settings Page:
![Screenshot 2023-04-03 at 8.27.46 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/68a23a25-9c60-4461-8e45-0cc25e74afae)
![Screenshot 2023-04-03 at 8.14.46 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/4d3bf21f-c91d-47ab-9ef5-e8af9f3a4ed6)

**Comment by junqiwu02** [comment]
Add as dependency of a user story

**Comment by junqiwu02** [comment]
This should be a blocking dependency not a blocked by

**Comment by junqiwu02** [comment]
Add a test to assert at it looks good from mobile
