### ISSUE TITLE
Integrate Weather API for the current weather into the Homepage

### ISSUE THREAD

**Issue by shlc001** [cse442-at-ub/project_s23-iweatherify#47]
**Tests**

*Test 1*
1) Visit the Website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/
2) See the Current Weather for Buffalo
3) Confirm that the data is the same using https://openweathermap.org/city/5110629
![Screenshot 2023-03-08 at 3.13.27 AM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/b4cd664b-ea3e-4365-b604-6dc715f0fe49)

*Test 2*
1) Visit the Website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/
2) In the input search bar type "Llanfairpwllgwyngyll"
3) Confirm that this div is scrollable
4) Confirm that the correct data is shown for the current weather using https://openweathermap.org/city/2644080
![Screenshot 2023-03-08 at 3.14.40 AM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/a2977b4f-f62b-4182-8b82-4d2d75e2bf79)

*Test 3*
1) Visit the Website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/
2) In the input search bar type "Manhattan"
3) Confirm that the Weather API Data is Shown!
4) Confirm the correct data is shown using this link: https://openweathermap.org/city/5125771
![Screenshot 2023-03-08 at 3.15.54 AM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/842d8965-193a-4a63-aed0-fa6769b6418b)

*Test 4*
1) Visit the Website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/
2) In the input search bar type ""
3) Confirm that nothing changes 

*Test 5*
1) Visit the Website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/
2) In the input search bar type "Buffal"
3) Nothing should change because that's not a city! and you should get an alert

*Test 6*
1) Visit the Website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/
2) In the input search bar type "Rome, US"
3) Confirm that the weather information is correctly displayed using https://openweathermap.org/city/4219762

**Comment by shlc001** [comment]
Need to update the API Key to use the paid dev edition (I just discovered that students get six months for free)

**Comment by junqiwu02** [comment]
Add a test for inputting a misspelled place and a place that doesn't exist. We want our app to be robust to incorrect input as well.

**Comment by junqiwu02** [comment]
Also I really like the Llanfairpwllgwyngyllh test LOL

**Comment by junqiwu02** [comment]
Also also this should be a blocking dependency, not a blocked by
