### ISSUE TITLE
As a person who likes to keep their location private, I want to disable my current location so I can maintain privacy

### ISSUE THREAD

**Issue by ccherian007** [cse442-at-ub/project_s23-iweatherify#49]
**Acceptance Tests**

_Test 1_

1. Open application at: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/
![Screenshot 2023-04-15 at 12.38.26 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/7c3e9366-33ed-4790-b996-7c97fbf5268a)
2. As a logged in user, navigate to location settings page
3. Set the toggle off if you do not want to share current location
![Screenshot 2023-04-15 at 8.23.09 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/96dc2a26-654a-4941-a4d0-9496d3d6e30f)

5. Click save button to save location settings
![Screenshot 2023-04-15 at 8.23.20 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/0bc8dd81-ca47-47b6-8816-75d124ae2d62) 

6. Verify this popup is shown to ensure disabled toggled is saved
![Screenshot 2023-04-15 at 8.25.16 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/8b3b9e66-d593-4090-9504-f6f289e89516)

_Test 2_

1. Repeat step 1 from Test 1

2. A popup will appear asking for live location and click **Don't Allow** to not share live location
![Screenshot 2023-04-15 at 8.31.05 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/eee969c3-50cb-48f3-a28e-243f06fff285)

3. Verify live location is not seen on the homepage 
![Screenshot 2023-04-15 at 8.33.21 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/32be94c2-2389-4ec4-9091-14fafa251a48)

**Comment by junqiwu02** [comment]
The test should have something to assert that the program is working. Also, I do not believe that this story is finished since we haven't implemented the functionality yet? Unless you guys are planning make it a different story.

**Comment by junqiwu02** [comment]
The title needs to follow "I want to [action] so that [outcome]". The tests need to assert something
