### ISSUE TITLE
As a person with unique temperature preferences, I want to categorize outfits based on different weather conditions, so that I can build a recommended outfit

### ISSUE THREAD

**Issue by ccherian007** [cse442-at-ub/project_s23-iweatherify#50]
**Acceptance Tests**

Test Setup: Visit https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#

*Test 1*
1) As a non-logged-in user visit the homepage

2) Click on "Open Options"
![Screenshot 2023-04-02 at 12.29.33 AM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/7115dcb1-a88e-4d27-833f-8c359256373a)

3) Click on Outfit of the day
![Screenshot 2023-04-02 at 12.31.21 AM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/09a4dff1-88a9-404f-a72b-e6edde708c05)

4) This should redirect you to the login page as a non-logged-in user

*Test 2*
1) As a logged-in user visit the homepage

2) Click on "Open Options" as was done in Test 1

3) Click on Outfit of the day, the menu should close automatically

4) As the default city is Buffalo currently, it should give you a text outfit recommendation placeholder based on the weather for Buffalo for the day as of now
![Screenshot 2023-04-02 at 12.33.09 AM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/7b57c276-bc78-4f92-8dc3-ede6c5a6cccc) 

*Test 3*
1) Continue being on the homepage as a logged-in user
2) Type in the city "Rome" in the search bar and press enter
3) It should automatically update the outfit recommendation (currently a placeholder) presuming the weather category is different
 ![Screenshot 2023-04-02 at 12.36.01 AM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/9d3a4b80-9278-4d80-8c04-050d46439ff6)

*Test 4*
1) Continue being on the homepage as a logged-in user
2) Click on Open Options and click on the 8-day Forecast
3) This should allow you to once again see the 8-day forecast component instead of the outfit of the day component

*Test 5*
1) Visit the my items page by visiting this link as a logged-in user: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/myItems
![Screenshot 2023-04-09 at 12.42.50 AM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/743dfadb-d022-4a1d-b7aa-e5b7eab598ef)
2) Confirm that if you click on each one of those options, it would take you to the desired location with subcategories shown in the following step
3) Confirm that Outerwear, Middlewear, Innerwear, Pants, Headwear, and Shoes are shown
![Screenshot 2023-04-09 at 12.44.14 AM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/b286f377-4ee6-4468-a2ab-5f5e57b40ff9)
4) Confirm that clicking on one of those categories takes you to a page with a plus sign, signifying to add
![Screenshot 2023-04-09 at 12.44.46 AM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/c73a24d0-23f0-40ec-8c66-e33f38b3d96e)
5) Click on the plus button and verify that a modal similar to this appears
![Screenshot 2023-04-09 at 12.45.06 AM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/4ca3ca4e-b639-4b45-a083-443fcdd29a7b)
6) You should be able to choose a file representing your image and be able to name the clothing item. Upload an image that is less than 2mb and should only have the extension of .jpg, .jpeg, or .png
7) Click on Save

*Test 6*
1) Do steps 1 -5 from test 5
2) Click on close Modal to confirm it closes
![Screenshot 2023-04-09 at 12.48.05 AM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/6616fc79-6825-4020-ba75-82da234d68ca)

*Test 7*
1) Do steps 1 - 5 from test 5
2) Only fill out the "Clothing name" input with something like: "Testing without image"
3) Click save
4) Verify that an error appears on the screen that you must upload an image with the name
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/13884a51-538d-47e6-9d88-3d6c697fe2b5)

*Test 8*
1) Follow steps 1 - 5 from Test 5. For the clothing name input value, type in something like: "Test 8 text"
2) Try uploading a .txt file when you click on the upload file button
3) Click save
4) Verify that there is an error preventing you from uploading
5) Click on the cancel button on the error modal
6) Redo steps 2 - 5 but with a .pdf file
7) Redo steps 2 - 5 but with a .pptx file
8) Redo steps 2 - 5 but with a .mp4 file
9) Redo steps 2 - 5 but with a .xlxs file
An example of what you can try to expect
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/3be75f73-1268-478f-aab7-4cebbb8ccb02)

*Test 9*
1) Follow steps 1 - 5 from Test 5
2) When you click on "Choose File", pick an image (.jpg, .jpeg, or .png) that is larger than 2MB. You can find this information by right-clicking on the image and clicking on properties if you are on Windows
3) Click save after you select this image
4) Ensure that you get an error that you can't upload the image

**Comment by junqiwu02** [comment]
title needs to follow "I want to [action] so that [outcome]". Tests need to be more detailed or with screenshots

**Comment by junqiwu02** [comment]
Remove the test where you open the console. Acceptance tests (in user stories) should be able to run by an untrained user.
