### ISSUE TITLE
Add state and interactivity to navbar for logged in and not logged in page 

### ISSUE THREAD

**Issue by ccherian007** [cse442-at-ub/project_s23-iweatherify#51]
Task Tests

_Test 1_

1. Go to the following URL: https://github.com/cse442-at-ub/project_s23-iweatherify/tree/dev

2. Click on the green <> Code button and download the ZIP file 
![Screenshot 2023-03-17 at 12.50.08 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/23c44a93-8f82-4919-bdf7-0578b7f3fa43)

3. Unzip the downloaded file to a folder on your computer

4. Open a terminal and navigate to the repository using **cd** command 

5. Run **npm install** command on the terminal to install the necessary dependencies

6. Run **npm start** command on the terminal to start the application

7. Check the output from the npm start command for the URL to view the application. The URL is a localhost address (e.g., http://localhost:8080) 

8. Navigate to http://localhost:8080

9. Verify the logged out page is shown as seen below: 
![Screenshot 2023-03-17 at 12.55.25 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/436a8cb9-a1df-41da-a4de-5b3a5f0ad6fb)

10. Click on the Profile Image Icon located on the right to direct you to to the login page
![default-profile-icon.png](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/d63726cb-03b0-4c6a-820b-f7d157ae6b87)

11: Verify the login page is shown as seen below: 
![Screenshot 2023-03-17 at 12.56.00 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/0b7e35c5-4519-496a-b21f-1233ff842716)

_Test 2_

1. Follow Steps 1-11 from Test 1 

2. Ensure you have logged in our application to see the homepage use UserID: **zal** and Password: **kal** to login 

3. Verify you see the homepage is shown as seen below: 
![Screenshot 2023-03-17 at 12.57.03 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/63802862-3275-4f4c-b350-b56dc3e148ce)

4. Click on the Profile Image to direct you to the Saved Outfits Page
![ellipse-6@2x.png](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/007302fc-eefb-4f05-907b-925de219648a)

5. Verify you can see the Saved Outfits page is shown as seen below: 
![Screenshot 2023-03-18 at 9.43.22 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/b5da53f5-ae61-4f4a-821f-2adf2a3e5023)

**Comment by junqiwu02** [comment]
Needs to be a dependency
