### ISSUE TITLE
Add button navigation functionality for the Menu

### ISSUE THREAD

**Issue by jhe48** [cse442-at-ub/project_s23-iweatherify#55]
**Tests**

What the Menu looks like: ![Screenshot 2023-03-15 at 11.17.23 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/27067f22-b609-48ff-8bd5-a325e5bb5e33)

*Test 1*
1) Go to https://github.com/cse442-at-ub/project_s23-iweatherify/tree/55_menu_button_nav
2) Click on <> Code
3) Download as a Zip
4) Follow the instructions in README.md on how to start and run on localhost
5) Observe that as a non-logged-in user on the homepage, the menu can be opened/closed by pressing the hamburger menu
![Screenshot 2023-03-15 at 11.01.21 PM.png]

*Test 2*
1) Follow Test 1 Up until (4)
2) Observe that as a logged-in user on the homepage, the menu can be opened/closed by pressing the hamburger menu
![Screenshot 2023-03-15 at 11.01.21 PM.png]

*Test 2*
1) Follow Test 1 Up until (4) 
2) From the homepage, click on the "register" button, it should take you to the register page
3) Confirm that the register button on the current registration page is not functional and is grayed out.
4) Return to the Homepage by clicking on that button and confirm it takes you to the non-logged-in homepage
5) From the homepage, click on the "login" button, it should take you to the login page
6) Confirm that the login button on the current login page is not functional and is grayed out.
7) Return to the Homepage by clicking on that button and confirm it takes you to the non-logged-in homepage

*Test 3*
1) Follow Test 1 Up until (4) 
2) From the Register Page, click on the "login" button, it should take you to the login page
3) From the Login Page, click on the "Register" button it should take you to the register page

*Test 4*
1) Follow Test 1 Up until (4)
2) Go to the login page using the button navigation
3) Enter the username "zal" and password "kal" and press Login
4) Confirm that The Homepage button is grayed out 
5) Click on the "Unit Settings" button, it should take you to the Unit Settings Page.
6) Open the Menu Once More and Click on Homepage confirming it's working 
7) From the Homepage click on "Temperature Settings" confirming that it takes you to the temperature settings page
8) Click on the Homepage to return

*Test 5*
1) Follow Test 4 up until (4)
2) Open the menu and click on the Unit Settings button to take you to the Unit Settings Page
3) From this page click on "Temperature Settings", it should take you to the appropriate page
4) From the "Temperature Settings" Page open the menu and click on "Unit Settings", it should take you to the unit settings page

*Test 6*
1) Follow Test 4 up until (4)
2) Click on the logout button, confirming it logs you out
3) Log back into your account with "zal" as the username "kal" as the password and login
4) Navigate to the Temperature Settings Page and click on log out from that page
5) Log back into your account with "zal" as the username "kal" as the password and login
6) Navigate to the Unit Settings Page and click on log out from that page
7) Confirm that Log Out Functions Properly 
![Screenshot 2023-03-15 at 11.17.02 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/8fd63e9d-eeb0-4f8c-ac60-97c6df9a0686)

**Comment by shlc001** [comment]
Improve the CSS styling as a separate task, this one (#55) focuses on the actual functionality of the menu

**Comment by shlc001** [comment]
Update 1: I need to update the log-out button to accommodate the changes that Valerie made. 

Update 2: The functionality of the menu all works. The front-end aspect of the log-out button also works (the auth_token is deleted). Although, it's not deleted from the database, as inserting the auth_token into the database doesn't appear to be working yet. When that's fixed a separate task can be made to delete the auth_token from the database
