### ISSUE TITLE
As a person who visits the site frequently, I want to navigate through the other pages of the website so that I can access more information and functionality.

### ISSUE THREAD

**Issue by jhe48** [cse442-at-ub/project_s23-iweatherify#58]
**Acceptance tests**

*Test 1*
1) Visit the website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/
2) Look at the top right corner of your screen
3) Click on the hamburger menu icon and open up the menu and ensure that the "Homepage" button is grayed out
![Screenshot 2023-04-14 at 5.36.24 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/dad98891-14f8-4c74-9728-594c1415e990)
4) Now, click the Register Button, which should take you to the Register Page
![Screenshot 2023-04-15 at 12.42.38 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/80488f32-f102-4298-98a6-e37c00507fed)
5) Open the hamburger menu again, and now click Login, that should take you to the Login Page
![Screenshot 2023-04-15 at 12.43.10 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/8b8635d8-3711-49ce-a7b8-0da65bf55bb3)
6) Open the Hamburger Menu Again, and make sure the Login button is disabled and grayed out. After that click the "Homepage" Button
![Screenshot 2023-04-15 at 12.43.43 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/c372c8a4-c626-4ca7-b58f-d7ff489e2a15)
7) Open the Hamburger Menu Again and ensure the "Homepage" button is disabled and grayed out

*Test 2*
1) Visit the website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/homepage as a logged-in user
2) Look at the top right corner of your screen
3) Click on the hamburger menu icon and open up the menu
4) The Homepage button should be disabled and grayed out
![Screenshot 2023-04-14 at 5.39.55 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/61d85ee2-bd41-4bec-a94d-897de0c30279)
4) Click on "My Items," which should take you to that page. Open the hamburger menu again and ensure the My Items Button is disabled
![Screenshot 2023-04-14 at 5.41.43 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/ce3de65f-ef9b-4088-8e00-a73bfa02e845)
5) Click on the "Saved Outfits" button, which should take you to that page. Open the hamburger menu again
![Screenshot 2023-04-15 at 12.47.43 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/22d1d3d9-ac32-4c33-9cd0-0604c344c067)
6) Open the menu and click on "Settings," it should take you to the Unit Settings page by default
![Screenshot 2023-04-15 at 12.48.04 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/772a37ef-f9f4-42ad-8949-0c00741e51d4)
7) Open the menu once more, ensuring that the "Settings" button is disabled, and click on Homepage, it should take you to the logged-in version of the homepage the path ends in /homepage
![Screenshot 2023-04-15 at 12.49.42 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/f42e58c9-de40-4264-b3de-1410002e8cd6)

*Test 3*
1) Visit the website https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/ as a logged-in user
2) Open the Hamburger Menu and click on the "Log Out Button"
![Screenshot 2023-04-15 at 12.50.22 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/0375808f-df2f-427c-a533-75dba50eede1)
3) It should automatically redirect you to the non-logged-in homepage
4) To verify, one can open up the hamburger menu to see the Options "Homepage" "Register" and "Login" signifying the user has logged out
![Screenshot 2023-04-15 at 12.51.10 PM.png](https://images.zenhubusercontent.com/63e16e3b1c90f75dc8056512/f66367ea-c093-4cbf-8123-b77e4b1eb930)

**Comment by shlc001** [comment]
The functionality and basic appearance of the button navigation are all there, but the menu still needs to be styled better (as a UI task)

**Comment by junqiwu02** [comment]
updated screenshots
