### ISSUE TITLE
Load unit and temperature setting from the database to the respective page when visited

### ISSUE THREAD

**Issue by JayXPan** [cse442-at-ub/project_s23-iweatherify#59]
**Task Tests**

*Test 1*
1. Go to the following URL: https://github.com/cse442-at-ub/project_s23-iweatherify/tree/dev
2. Click on the green `<> Code` button and download the ZIP file.
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/75c741f7-5ca3-4f64-879f-df960ad51a8b)
3. Unzip the downloaded file to a folder on your computer.
4. Open a terminal and navigate to the git repository folder using the `cd` command.
5. Run the `npm install` command in the terminal to install the necessary dependencies.
6. Run the `npm start` command in the terminal to start the application.
7. Check the output from the npm start command for the URL to access the application. The URL should be a localhost address (e.g., http://localhost:8080).
8. Navigate to http://localhost:8080/#/login
9. Ensure you have logged in to our app to see the page use UserID: `UB442` and Password:`Myub442@!` to login
10. Go to URL: http://localhost:8080/#/unitsSettings
11. Verify that the units page is displayed
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/3f9cbb63-e582-43f0-91bf-16970daf57eb)
12. Change the temperature unit to Celsius (°C)
13. Change the wind unit to mph
14. Change the pressure unit to mm
15. Change the distance unit to mi
16. Click the save button
17. Open a different tab and go to: https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/index.php
18. Input username: `jpan26` and password: `50314999`
19. Make sure the server choice is `oceanus.cse.buffalo.edu:3306`
20.  Click go and you should see this page 
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/443bf59a-f5fd-4dbe-88a8-645493eaa713)
21. Click `cse442_2023_spring_team_a_db` first and then `saved_units` on the left side of the page
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/9cb87c0a-e93f-4327-9640-8f6c0478c3a2)
22. Verify you see a row with the exact same information shown by the picture
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/1f326a8d-6adc-4863-ba2f-2dac935fe23b)
23. Go back to the units page you can press 'F5' to refresh the page and you should see the same units you saved previously on the the page
24. You can log out and log back in and go to units page
25. You should still see the saved same unit settings on the page

*Test 2*
1. Repeat steps 1 to 9 from `Test 1`
2. Go to URL: http://localhost:8080/#/tempSettings
3. Verify that the temperature setting page is displayed
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/1feae072-4846-46ae-8639-9958248e9158)
4. Change the hot temperature to 100, you can either use the slider or input box and click save
5. Change the warm temperature to 75, you can either use the slider or input box and click save
6. Change the ideal temperature to 25, you can either use the slider or input box and click save
7. Change the chilly temperature to 10, you can either use the slider or input box and click save
8. Change the cold temperature to -25, you can either use the slider or input box and click save
9. Change the freezing temperature to -75, you can either use the slider or input box and click save
10. Repeat steps 17 to 20 from `Test 1`
11. Click `cse442_2023_spring_team_a_db` first and then `saved_temperatures` on the left side of the page
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/ae9e6ed8-1291-4690-89ab-ce8cb4223843)
12. Verify you see a row with the exact same information as shown by the picture
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/16b1d57f-5c20-4bb0-b4fa-82833da6ca95)
23. Go back to the temperature setting page you can press 'F5' to refresh the page and you should see the same temperatures you saved previously on the the page
24. You can log out and log back in and go to temperature settings page
25. You should still see the saved same temperatures on the page

**Comment by junqiwu02** [comment]
Needs tests and dependency
