### ISSUE TITLE
Make Design for Menu

### ISSUE THREAD

**Issue by jhe48** [cse442-at-ub/project_s23-iweatherify#62]
**Task Tests**

*Test 1*

1. Navigate to https://github.com/cse442-at-ub/project_s23-iweatherify/tree/62_Make_Design_for_Menu

2. Click on the green "<> Code" button and select "Download Zip" to download zip file:
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/e0198c0a-f6ba-4769-8898-bdc15868c2e9)

3. Unzip the file to a folder on your computer

4. Open a terminal and locate the git repository folder using **cd** command

5. Run **npm install** to install necessary dependencies 

6. Run **npm start** to start the application

7. Open the application in a web browser using the localhost that was generated by npm. 

8. Locate and click on the hamburger menu: 
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/ebdb03ba-f7c9-4005-ab21-487538cff062)

9. Verify you can see this drop down menu after clicking the hamburger menu: 
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/0cb7674f-5719-43cb-814d-8b2e9b093774)

*Test 2*

1. Repeat Steps 1-8. 

2. Login with details: 
Username: zal
Password: kal
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/1a14e399-f58d-4d02-a37b-a01095b46445)

3. Locate and click on the hamburger menu: 
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/14306cb9-cfc3-4f29-aeb2-a4ba1fe08fc6)

4. Verify you can see this drop down menu after clicking the hamburger menu: 
![image.png](https://images.zenhubusercontent.com/63e1bdc649ab52516797d7dc/ede23efa-a0e2-4b91-ac9c-0d3ccdcfdb1e)

**Comment by shlc001** [comment]
(Had to disable Incomplete Menu Options for pages that are being carried over to sprint 3 as they were never fixed for responsiveness)
