### ISSUE TITLE
Add state and interactivity to Location Setting page 

### ISSUE THREAD

**Issue by ccherian007** [cse442-at-ub/project_s23-iweatherify#65]
Task Tests

**Test 1**

1. Navigate to application with this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/?#/homepage
![Screenshot 2023-04-15 at 12.38.26 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/7c3e9366-33ed-4790-b996-7c97fbf5268a)
2. After logging in, navigate to Location Settings Page

3. Disable toggle to not share current location 
![Screenshot 2023-04-03 at 9.02.41 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/464a6d00-3739-4608-a880-7e1f74fa9f78)

4. Click save button to save changes
![Screenshot 2023-04-03 at 9.04.09 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/9e931ae7-4570-4289-b33b-51b973733ff2)

5. Make sure this popup is shown to ensure the toggle has been disabled and saved 
![Screenshot 2023-04-15 at 4.53.18 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/07907bcb-f05c-42ce-bb50-ad1a9388436f)

6. Go back to Location Settings page to verify toggle is disabled 
![Screenshot 2023-04-15 at 10.08.00 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/921ef084-a529-450e-aa45-5cd546b80d82)

**Test 3**
1. Repeat steps 1-2 from Test 1 

2. Enter any city of your choice 
![Screenshot 2023-04-15 at 4.48.23 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/fd2283fe-0dff-4366-a328-e2fad02dbcaa)

3. Click save button to save changes. 
![Screenshot 2023-04-03 at 9.04.09 AM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/9e931ae7-4570-4289-b33b-51b973733ff2)

4. Make sure this popup is shown to ensure the new city is saved 
![Screenshot 2023-04-15 at 4.53.18 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/07907bcb-f05c-42ce-bb50-ad1a9388436f)

5. Go to homepage to see new city with accurate weather reporting of that city. 
![Screenshot 2023-04-15 at 4.51.49 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/b013c49a-6507-48b9-80ca-2ecef1b25acc)

6. Go back to Location Settings page and verify the new location is in location preferences 
![Screenshot 2023-04-15 at 10.03.57 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/71dfbdc4-f01b-4862-a04b-e7b19d8ac533)

**Comment by junqiwu02** [comment]
The tests need to assert something. For example: refresh the page and assert the preferences were saved.

**Comment by junqiwu02** [comment]
add a test for visiting the page again and ensuring the user's existing data is loaded into the page
