### ISSUE TITLE
As a person who often makes mistakes, I want to see error prompts directly on the page so that I can quickly understand and correct any issues

### ISSUE THREAD

**Issue by JayXPan** [cse442-at-ub/project_s23-iweatherify#66]
**Acceptance Tests**

*Test 1*
1. Open a broswer and go to this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/register
2. Ensure all fields are empty
3. Click the `Register` button.
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/3790082e-da39-40a7-913b-e5d19e00aa7f)
4. Ensure that the modal box with the message `Please fill all required information` appears.
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/280a537d-1957-4328-ad2e-bc3aa59898e9)
5. Click the `Cancel` button to close the modal.
6. Verify that all required fields are now highlighted in red to indicate missing information.
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/b2da0309-fa0b-4f4c-98fe-dccc2f0c758f)

*Test 2*
1. Open a broswer and go to this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/register
2. Enter `UB442_1@buffalo.edu` into the email field
3. Leave username and password fields empty
4. Click the `Register` button
5. Ensure that the modal box with the message `Username and password are empty` appears
6. Click the `Cancel` button to close the modal.
7. Verify that username and password fields are highlighted in red to indicate missing information

*Test 3*
1. Open a broswer and go to this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/register
2. Enter `UB442_1` into the username field
3. Leave email and password fields empty
4. Click the `Register` button
5. Ensure that the modal box with the message `Email address and password are empty` appears
6. Click the `Cancel` button to close the modal.
7. Verify that email and password fields are highlighted in red to indicate missing information

*Test 4*
1. Open a broswer and go to this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/register
2. Enter `UB442_1@!#$` into the password field
3. Leave email and username fields empty
4. Click the `Register` button
5. Ensure that the modal box with the message `Email address and username are empty` appears
6. Click the `Cancel` button to close the modal.
7. Verify that email and username fields are highlighted in red to indicate missing information

*Test 5*
1. Open a broswer and go to this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/register
2. Enter `UB442_1` into the username field and enter `UB442_1@!#$` into the password field
3. Leave email field empty
4. Click the `Register` button
5. Ensure that the modal box with the message `Please enter an email address` appears
6. Click the `Cancel` button to close the modal.
7. Verify that email field is highlighted in red to indicate missing information

*Test 6*
1. Open a broswer and go to this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/register
2. Enter `UB442_1@buffalo.edu` into the email field and enter `UB442_1@!#$` into the password field
3. Leave username field empty
4. Click the `Register` button
5. Ensure that the modal box with the message `Please enter an username` appears
6. Click the `Cancel` button to close the modal.
7. Verify that username field is highlighted in red to indicate missing information

*Test 7*
1. Open a broswer and go to this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/register
2. Enter `UB442_1@buffalo.edu` into the email field and enter `UB442_1` into the username field
3. Leave password field empty
4. Click the `Register` button
5. Ensure that the modal box with the message `Please enter a password` appears
6. Click the `Cancel` button to close the modal.
7. Verify that password field is highlighted in red to indicate missing information

*Test 8*
1. Open a broswer and go to this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/register
2. Enter `UB442_1` into the email field
3. Enter `UB442_1` into the username field
4. Enter `UB442_1@!#$` into the password field
5. Click the `Register` button
6. Ensure that the modal box with the message `Please enter a valid email address` appears
7. Click the `Cancel` button to close the modal.
8. Verify that email field is highlighted in red to indicate wrong information

*Test 9*
1. Open a broswer and go to this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/register
2. Enter `UB442_1@buffalo.edu` into the email field
3. Enter `442` into the username field
4. Enter `UB442_1@!#$` into the password field
5. Click the `Register` button
6. Ensure that the modal box with the message `Your username must contain at least one character` appears
7. Click the `Cancel` button to close the modal.
8. Verify that username field is highlighted in red to indicate wrong information

*Test 10*
1. Open a broswer and go to this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/register
2. Enter `UB442_1@buffalo.edu` into the email field
3. Enter `UB442_1` into the username field
4. Enter `UB442_1!` into the password field
5. Click the `Register` button
6. Ensure that the modal box with the message `Your password needs to be at least 9 characters long` appears
7. Click the `Cancel` button to close the modal.
8. Verify that password field is highlighted in red to indicate wrong information

*Test 11*
1. In the web browser, navigate to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/login
2. Ensure all fields are empty
3. Click the `Login` button
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/894849bd-5c6a-43dd-bcf8-484e19b90765)
4. Ensure that the modal box with the message `Make sure you fill both username and password` appears
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/e6b5e239-a29c-4903-8abb-142a156d88f4)
5. Click the `Cancel` button to close the modal.
6. Verify that all required fields are now highlighted in red to indicate missing information.
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/a90d667b-f25c-48ae-a522-4f2a1cb0aa6a)

*Test 12*
1. In the web browser, navigate to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/login
2. Enter `UB442` into username field and `UB442HERTZ@!` into the password field
3. Click the `Login` button
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/894849bd-5c6a-43dd-bcf8-484e19b90765)
4. Ensure that the modal box with the message `Invalid username and/or password` appears
5. Click the `Cancel` button to close the modal.
6. Verify that all required fields are now highlighted in red to indicate wrong information.

*Test 13*
1. Repeat same `Test 1` in Task #108 except in step 2 log in with the username: `UB442_User3` and password: `Myub442@!`

*Test 14*
1. Repeat same `Test 2` in Task #108 except in step 2 log in with the username: `UB442_User3` and password: `Myub442@!`

*Test 15*
1. Repeat same `Test 3` in Task #108 except in step 2 log in with the username: `UB442_User3` and password: `Myub442@!`

*Test 16*
1. Repeat same `Test 4` in Task #108 except in step 2 log in with the username: `UB442_User3` and password: `Myub442@!`

*Test 17*
1. Repeat same `Test 5` in Task #108 except in step 2 log in with the username: `UB442_User3` and password: `Myub442@!`

*Test 18*
1. Repeat same `Test 6` in Task #108 except in step 2 log in with the username: `UB442_User3` and password: `Myub442@!`

*Test 19*
1. Repeat same `Test 7` in Task #108 except in step 2 log in with the username: `UB442_User3` and password: `Myub442@!`

**Comment by junqiwu02** [comment]
"site visitor" is a bit too general of a description, something like "user who makes mistakes" is more appropriate.

**Comment by JayXPan** [comment]
Fixed
