### ISSUE TITLE
Create Static Vue Page for Account Settings for Desktop and Mobile

### ISSUE THREAD

**Issue by jhe48** [cse442-at-ub/project_s23-iweatherify#69]
**Tests**

*Test 1*

1. Navigate to application on desktop: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/homepage

2. Make sure your logged in, and navigate to Account Settings Page

3. Validate entire Account Settings Page is shown 
![Screenshot 2023-04-22 at 3.05.54 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/d68c2795-31ef-415c-b434-ae837b8eba78)

**Test 2**

1. Navigate to application.: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/homepage

2. Make sure your logged in, and navigate to Account Settings Page

3. Click inspect and select mobile view. And select iPhone12 Pro. 
![Screenshot 2023-04-22 at 4.16.24 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/d3701a9f-06c4-4522-a1ad-60fe6a63f96d)

4. Validate entire Account Settings Page is shown 
![Screenshot 2023-04-22 at 3.04.58 PM.jpg](https://images.zenhubusercontent.com/63e1bd62372e8c7d6b7faaf7/66f7b68f-3eb4-4eaa-b450-1573a5228b01)

**Comment by junqiwu02** [comment]
add dependency
