### ISSUE TITLE
As a person with unique temperature preferences, I want to input how I feel about certain temperature ranges, so that I can see when a day is too hot/cold/just right based on my preferences.

### ISSUE THREAD

**Issue by vwong175** [cse442-at-ub/project_s23-iweatherify#7]
**Acceptance tests** 

*Test 1*
1. Open a broswer and go to this URL: https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/
2. Login with this username: `UB442` and password `Myub442@!`
3. Navigate to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/tempSettings
4. Input your desired temperature between -100 and 100 for hot in the input box or you can also use the slider to set it
5. Click the save button to save your temperature preference
6. You can repeat steps 4 and 5 for: warm, ideal, chilly, cold, and freezing
7. You should the message: `Temperatures Saved Successfully` for each of them after clicking save button
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/ff36a442-9500-479c-b428-84bb10ab1415)
7. Press `F5` to refresh the temperature setting page 
8. Verify you see the same temperatures you saved for each temperature zone

*Test 2*
1. Repeat steps 1 and 2 from `"Test 1"`
2. Navigate to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442a/#/unitsSettings
3. Click on the drop-down menu for temperature and select your desired temperature unit
4. Click on the drop-down menu for wind and select your desired wind unit
5. Click on the drop-down menu for pressure and select your desired pressure unit
6. Click on the drop-down menu for wind and select your desired distance unit
7. Click the save button and you will see this message: `Units saved successfully.`
![image.png](https://images.zenhubusercontent.com/63e1796387907702186b8c6a/ab898d40-b178-4a36-939d-77945e980ce4)
8. Press `F5` to refresh the units page
9. Verify you see the same units that you selected and saved from steps 3 to 6.

**Comment by junqiwu02** [comment]
change screenshot to the actualy website instead of localhost
