### ISSUE TITLE
Make My Items pages responsive for mobile

### ISSUE THREAD

**Issue by vwong175** [cse442-at-ub/project_s23-iweatherify#70]
**Task Tests**

*Test 1*
1) Go to repo: https://github.com/cse442-at-ub/project_s23-iweatherify/tree/dev, git clone it and `cd` into the root of the project. Run `npm install` and `npm install`
2) Click on the hamburger menu, click on login and login with the credentials of "demo123" as the username and "Demo123456!" as the password
3) In the URL, add "/myItems"
4) Right-click anywhere on the page and click on Inspect
5) Click on the phone/tablet icon and click on the dropdown menu for different phones. Start with iPhone SE and ensure that none of the content of the page gets cut off of the frame. Do the same with all the other mobile options in the dropdown list. Close the inspect panel to ensure that the desktop view provides the same content while also not being out of the frame of the desktop screen.
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/0415a070-f7ae-4d8e-ad1a-edecf410fff0)
The mobile version of the page should look something like this when you test with the iPhoneSE option
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/db11cb05-59f2-469c-99f9-86e9739612d0)
The desktop version should look similar to this when you exit out of the inspect element
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/8c613833-16ef-4ae3-a8d9-10dffeb86899)
6) Repeat steps 3 - 5 but replace the end of the URL string in step 3 with "/myItems/hot"
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/fe576d5e-ac83-47f7-9d81-f4a8d3653c2b)

The desktop version should look similar to this:
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/43b06e1a-a605-4690-84a3-917d37c9005b)
7) Repeat steps 3 - 5 but replace the end of the URL string in step 3 with "/myItems/warm"
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/8d272dfd-fdf0-478b-bcd9-99737f9ff6cb)
8) Repeat steps 3 - 5 but replace the end of the URL string in step 3 with "/myItems/justRight"
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/8f815aa3-1993-4fb1-a8fa-b640ac523552)
9) Repeat steps 3 - 5 but replace the end of the URL string in step 3 with "/myItems/chilly"
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/eb9eb414-d50f-4f67-91ca-9583be9b98a4)
10) Repeat steps 3 - 5 but replace the end of the URL string in step 3 with "/myItems/cold"
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/5ed20937-02aa-4c7c-b24d-85a8339c38f7)
11) Repeat steps 3 - 5 but replace the end of the URL string in step 3 with "/myItems/freezing"
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/6dff8dcd-f7e7-4c67-91b6-bbb61bc3002a)
12) Repeat steps 3 - 5 but replace the end of the URL string in step 3 with "/myItems/hot/outerwear"
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/3b6ad4aa-a712-48fb-a287-8b03e6ca9d49)
13) Repeat steps 3 - 5 but replace the end of the URL string in step 3 with "/myItems/hot/middlewear"
14) Repeat steps 3 - 5 but replace the end of the URL string in step 3 with "/myItems/hot/innerwear"
15) Repeat steps 3 - 5 but replace the end of the URL string in step 3 with "/myItems/hot/pants"
16) Repeat steps 3 - 5 but replace the end of the URL string in step 3 with "/myItems/hot/headwear"
17) Repeat steps 3 - 5 but replace the end of the URL string in step 3 with "/myItems/hot/shoes"
19) Repeat steps 12 - 17 but rather than "hot", replace it with "warm"
20) Repeat steps 12 - 17 but rather than "hot", replace it with "justRight"
21) Repeat steps 12 - 17 but rather than "hot", replace it with "chilly"
22) Repeat steps 12 - 17 but rather than "hot", replace it with "cold"
23) Repeat steps 12 - 17 but rather than "hot", replace it with "freezing"

**Comment by junqiwu02** [comment]
add some screenshots or elaborate further on how to page responds, since mobile useability goes beyond simply where no content gets cut off
