### ISSUE TITLE
Pull images from My Items table and display them in their respective My Items subpages  

### ISSUE THREAD

**Issue by vwong175** [cse442-at-ub/project_s23-iweatherify#80]
**Task Tests**

*Test 1*
1) Go to repo: https://github.com/cse442-at-ub/project_s23-iweatherify/tree/dev
2) Git clone and cd into the root of the repo
3) Run `npm install` and `npm run start`
4) Click on the hamburger menu on the top right-hand corner and click on login
5) Login with the credentials of "sprint4" as the username and "Sprint1234!" as the password
6) Go to the hamburger menu and click on My Items
7) Click on Hot
8) Click on outerwear
9) Verify that you can see a plus button as well as any other image on the page
10) Click on the back button in the browser
11) Click on middle wear
12) Verify that the contents of the page here is different from what was presented in step 9
14) While staying in middle wear, click on the plus button located on the bottom of the page, for the clothing name type in "Adding image test" and for the image upload another image that is under 2mb with either a .jpeg, .jpg, or .png extension and then click save. Here is a google drive link of sample images you can use: https://drive.google.com/drive/folders/16Yt24NnqS7iIZqVUTMDCddWzzvLVYr0o?usp=sharing
15) Refresh the page
16) Verify that there exists a new image and clothing item name that matches the contents that you did in step 14

*Test 2*
1) Follow steps 1 - 9 from test 1
2) Click on the plus button for the clothing name type in "Testing multiple images". For the image upload, click on "Choose file" and pick an image that is less than 2mb and has an extension of .jpg, .jpeg, or .png
3) Click on save
4) Refresh the page
5) Verify that there is a new image and clothing item name on the page in addition to any previous photos and clothing item names that were previously on the page in step 1
6) Repeat steps 2 - 5 three more times but change the image to be a different image when you repeat step 2
7) After you uploaded 3 more times, verify that none of the clothing item names overlap on an image
For example: 
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/124cfb64-9b0e-490b-bb3e-c7a0dc04c331)

*Test 3*
1) If you did not do test 2 before this test, do that first. Otherwise, repeat steps 1 - 9 from test 1
2) Right click anywhere on the page and then click on inspect element
3) Click on the phone/tablet icon
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/6ccf76e0-cf3a-4e99-b42f-82a916f74105)
4) In the text to the right of responsive, go through each of the mobile devices and ensure that all of the contents of the page stays within the borders of the view frame
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/41b56fb6-1ad1-42d7-b35f-8ad8b892b32f)
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/5bf0cbca-f9b0-4b98-8623-757fd3da7230)
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/163cabae-0684-431e-a7a3-5e02f8766b19)

**Comment by junqiwu02** [comment]
add a test to ensure the formatting (on mobile and desktop) works when there's many my items.
