### ISSUE TITLE
As a beginner participant, I want to interact with a design prototype, so that I can see the user experience of going through the app

### ISSUE THREAD

**Issue by vwong175** [cse442-at-ub/project_s23-iweatherify#9]
**Acceptance tests**

*Test 1*
1) Follow the tests in task #8

*Test 2*
1) Follow the tests in task #10

*Test 3*
1) Follow the tests in task #11

*Test 4*
1) Follow the tests in task #12

*Test 5*
1) Follow the tests in task #13

*Test 6*
1) Open the Figma file for iWeatherify using this link: https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=0bYV0rMFBe8FbA2l-1
2) Click on the "Play" button, top right of the page, to start the interactive demo, and select "Desktop - logged in" to begin the flow
![Play Button](https://user-images.githubusercontent.com/112517521/219908195-3048cb15-ff44-4e60-9875-9c86cdd8ad07.png)
![Desktop flow - logged in](https://user-images.githubusercontent.com/112517521/219908246-b6684815-b990-462d-b6cc-2c5b8cdb8cc5.png)
3) Click on "Save" button in the outfit of the day card
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/12071dba-911f-487c-b7fc-1c09379640b7)
4) Verify that a confirmation modal pops up on the screen stating that the outfit has been saved
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/01e059c2-aec8-4650-a311-b77a5ebab9a6)

*Test 7*
1) Open the Figma file for iWeatherify using this link: https://www.figma.com/file/MezZn3xcEGiUnMHzpY7ton/iWeatherfy?node-id=374%3A672&t=0bYV0rMFBe8FbA2l-1
2) Click on the "Play" button, top right of the page, to start the interactive demo, and select "Desktop - not logged in" on the left hand side panel
![Play Button](https://user-images.githubusercontent.com/112517521/219908195-3048cb15-ff44-4e60-9875-9c86cdd8ad07.png)
3) Verify that you see a landing screen with location, temperature, forecast from now to eight hours in advance, and a blurred pop-up incentivizing you to login.
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/3675c977-db61-403c-ad0e-fe842d5680b4)

*Test 8*
1) Follow steps 1 through 2 from test 7
2) Click on the profile picture located on the top right hand corner
3) Verify that you have been brought to a login screen with a login form
4) Verify that the login form has two input elements, one for the username and one for the password
5) Click on "Create account" located under the "Login" button
6) Verify that you have been brought to a new page with the header "Register" and a register form with two input elements: "Username" and "Password"
7) Click on "Login" and verify that you have been brought back to the same login page as before

*Test 9*
1) Follow steps 1 through 2 from test 7
2) Click on the hamburger menu located on the top right hand corner
3) Verify that you have been brought to a new page with the header "Login" and a login form with two inputs: "Username" and "Password"

*Test 10*
1) Follow steps 1 through 4 from test 8
2) Click the "Login" button
3) Verify that you see a landing screen with location, temperature, forecast from now to eight hours in advance, and a suggested outfit card
4) Verify that the profile component on the top right hand corner has a picture in it
![image.png](https://images.zenhubusercontent.com/63e1b1173ed7400970e2ed9d/c5af8004-6ed9-436a-89d8-769f214c79a0)

*Test 11*
1) Follow the steps from Test 1 from #12
2) Click on "My Items" from the menu
3) Click on "Hot"
4) Verify that you are brought to a new page with 6 categories of clothing: "Outer layer", "Middle layer", "Inner layer", "Bottoms", "Head wear", and "Shoes"
5) Click on the hamburger menu on the top right hand corner and click on "My Items"
6) Click on "Warm" and verify that the 6 categories of clothing mentioned in step 4 are also in this page
7) Redo step 5, click on "Just right" and verify that the 6 categories of clothing mentioned in step 4 are also in this page
9) Redo step 5, click on "Chilly" and verify that the 6 categories of clothing mentioned in step 4 are also in this page
10) Redo step 5, click on "Cold" and verify that the 6 categories of clothing mentioned in step 4 are also in this page
11) Redo step 5, click on "Freezing" and verify that the 6 categories of clothing mentioned in step 4 are also in this page

*Test 12*
1) Follow the tests from task #28

*Test 13*
1) Follow the tests from task #29

*Test 14*
1) Follow the tests from task #30

*Test 15*
1) Follow the tests from tasks #31

*Test 16*
1) Follow the tests from tasks #32

*Test 17*
1) Follow the tests from tasks #34

*Test 18*
1) Follow the tests from tasks #35

**Comment by junqiwu02** [comment]
"Click on any of the flows" and "Start interacting with the navigation bar and buttons" is too generalized to be a proper test. A way you can make the story tests comprehensive without restating previous tests is to say something like: "Test 1: Follow task tests in tasks X, Y, and Z" and then add any other tests you need.

**Comment by junqiwu02** [comment]
Add assignees, should be whoever worked on the dependent tasks
